[package]
name = "aws-lambda-rust-runtime-0"
version = "0.1.0"
authors = ["leodamsky <vadim.leodamsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
